### ISSUE TITLE
after opening ticket by visitor

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#10]
after opening ticket , anything visitor is typing is not coming to the conversation on chat box , it need to reload the page in order to appear , 

https://user-images.githubusercontent.com/88825506/129191611-d88aa9e5-513f-4aec-b211-f88899f07c00.mp4

**Comment by navid-farjad** [comment]
deployed

**Comment by RezaUFC** [comment]
Done, Working as is expected.
