### ISSUE TITLE
agent dashboard issue

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#11]
After the visitor created a ticket, sending messages is not appearing on the 
agent dashboard chat page, it needs to reload the page in order to see new messages. 

https://user-images.githubusercontent.com/88825506/129193040-74d19921-769c-44a0-bc42-20586492ead8.mp4

**Comment by navid-farjad** [comment]
deployed

**Comment by RezaUFC** [comment]
Done, Working as is expected.
