### ISSUE TITLE
Call is not working

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#13]
Call from the visitor which has a ticket open is not showing on the agent dashboard incoming calls
![photo_2021-08-12_15-21-16](https://user-images.githubusercontent.com/88825506/129195962-ec39f0b9-51eb-430a-a6e2-b6ba6e995163.jpg)

**Comment by pureinx** [comment]
@RezaUFC please retest it after new changes is deployed

**Comment by navid-farjad** [comment]
deployed
