### ISSUE TITLE
sales-message section not taking css, how can we add our css in third party sites for this section

### ISSUE THREAD

**Issue by harmeetsinghD4D** [navid-farjad/yollochat#14]
![Screenshot_1](https://user-images.githubusercontent.com/68951644/129316059-09081f29-dea8-4739-bf37-625e3e56bb6b.png)
![Screenshot_2](https://user-images.githubusercontent.com/68951644/129316066-df2ec25e-ded0-47fe-8aed-d8a45c836bcf.png)

**Comment by pureinx** [comment]
Using inline styles @harmeetsinghD4D

**Comment by navid-farjad** [comment]
this is closed?
