### ISSUE TITLE
 Attachment files not visible in visitor chat and mini chat

### ISSUE THREAD

**Issue by harmeetsinghD4D** [navid-farjad/yollochat#15]
![Screenshot_1](https://user-images.githubusercontent.com/68951644/129317325-e4753521-023a-4c39-9843-64ea66d662f7.png)
![Screenshot_2](https://user-images.githubusercontent.com/68951644/129317332-545bb2b2-2fff-4c9a-abf6-29fdca9e9469.png)

**Comment by pureinx** [comment]
@navid-farjad probably it is backend issue for visitor-sales chat. Here is screenshots what I send and what I get in messages: 
<img width="373" alt="Screenshot 2021-08-13 at 12 35 57" src="https://user-images.githubusercontent.com/20497948/129337507-e629eba7-aaa3-4de8-9dab-e2ea024cd3d6.png">
<img width="465" alt="Screenshot 2021-08-13 at 12 36 14" src="https://user-images.githubusercontent.com/20497948/129337515-2c692f28-e5e3-44b1-bc4d-8f86d1ff32b1.png">

**Comment by navid-farjad** [comment]
fixed
