### ISSUE TITLE
Visitor calling Bugs

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#18]
After the agent starts a conversation with a visitor, the visitor will decide to make a call, which there are some bugs as you can see on the screenshot.
1. on the target website mini chat, after the call is connected, there is just a dark box without any information, or it looks like it just appearing the information under the dark box is not visible.
2. Calling duration for timing is not working as is expected. does not show running time for the call. just staying on 00:00
3. the name of the visitor which as default is "Visitor_336" is not appearing on the call, as you see the is just a "USER" with unloaded Icone. 
4. the option for "open conversation" / when we are on the conversation already !!! why do we need to see an option for opening the conversation??? 

Suggestion: if we are on the conversation which it will show on the top bar of conversation on the agent dashboard the calling information!!! there is no need for popup calling info to appear. this will have logic only if the agent during the call opens another tab. 
![image](https://user-images.githubusercontent.com/88825506/129441342-4f9901bd-ae6d-466b-bd37-9c46abdb5778.png)

**Comment by navid-farjad** [comment]
open conversation should be open ticket. we need it as agent can move between tabs during the call

**Comment by navid-farjad** [comment]
the name should be "visitor" or "client" we need to update them by socket

**Comment by navid-farjad** [comment]
i approve 1 & 2 as a bug
