### ISSUE TITLE
Call Duration recording

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#19]
After Call is done, as is expected, the call conversation need to be recorded and added as a note for the agent

**Comment by navid-farjad** [comment]
@pureinx we have system event type 6 in messages as note, i have html description in the message please show it in the list. its recorded call

**Comment by pureinx** [comment]
@navid-farjad done

**Comment by RezaUFC** [comment]
Call recording is not working yet. @navid-farjad @pureinx
