### ISSUE TITLE
add id in visitor list

### ISSUE THREAD

**Issue by navid-farjad** [navid-farjad/yollochat#2]
Expected Behavior
list of visitor has NA ain list , we need to add internal id 
Current Behavior

Steps to Reproduce
i will create backend internal_id and show it there in front end 
Context (Environment)
beta

**Comment by navid-farjad** [comment]
adding internal_id to visitor object

**Comment by pureinx** [comment]
<img width="1792" alt="Screenshot 2021-08-13 at 17 23 09" src="https://user-images.githubusercontent.com/20497948/129371840-f252fb07-5637-4186-996b-d6c8f251e5e6.png">

@navid-farjad  Added Id in visitors list, field name is visitor.internal_id

**Comment by pureinx** [comment]
Done
