### ISSUE TITLE
Agent needs

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#21]
As an agaent I think I need to have availability of changing or updating the information of my customers which they open a ticket, 
as you see in the sample of photo, I put wrong information, so how can I change it in the dashboard? 
![image](https://user-images.githubusercontent.com/88825506/129442314-47534f35-3070-43ac-856d-1b6570eedab2.png)

**Comment by navid-farjad** [comment]
subject is editable , if you have an update in information you can create a new note in your chat, we will add ability to edit note soon

**Comment by RezaUFC** [comment]
The subject is about the ticket, which will explain in a short way. 
But the Name / Email / Phone Number is the data that user can enter on the form to start the chat or if as a visitor agent need to be able to edit or add this main information for each one of them (We have this function on live visitor chat).
As I see the subject is taking action as a name, which I think is not correct.
