### ISSUE TITLE
NEW 1 - Sending photo not working!

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#30]
If an agent wants to send a photo from the dashboard chat (Live visitor), is not working. 

https://user-images.githubusercontent.com/88825506/129681154-a2cd0fab-07fd-4276-86fd-4f0964dc9994.mp4

**Comment by pureinx** [comment]
done and deployed

**Comment by RezaUFC** [comment]
I think user on mini chat has be able to click and open sent pictures in order to zoom and see details. at the moment photos are not clickable. 

![image](https://user-images.githubusercontent.com/88825506/129907011-907e9e37-2353-4d0e-897e-c2a710b1479c.png)

**Comment by navid-farjad** [comment]
@pureinx for chatroom lets remove adding image by quill

**Comment by RezaUFC** [comment]
Yes, Think is better to remove it. bcuz the is no reason when an agent can send the attachment.
