### ISSUE TITLE
NEW 4 - Unread Messages 

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#33]
The number assign as unread messages, is showing the number of actual messages in the conversation, 

![image](https://user-images.githubusercontent.com/88825506/129692173-af602c9a-67ee-4dd3-ace0-4f4148d45a1a.png)

![image](https://user-images.githubusercontent.com/88825506/129692276-8d0e4b45-e87e-4633-acf9-761a395ac9b1.png)

**Comment by navid-farjad** [comment]
@pureinx probably you dont send read request to api

**Comment by pureinx** [comment]
@navid-farjad now I send but count didnt changed
