### ISSUE TITLE
live visitor does not have style 

### ISSUE THREAD

**Issue by navid-farjad** [navid-farjad/yollochat#5]
Expected Behavior
we need css for it 
Current Behavior
![image](https://user-images.githubusercontent.com/30972233/129184918-7260f283-c55f-4100-8fa5-826ca3996be3.png)

Steps to Reproduce
Context (Environment)

**Comment by RezaUFC** [comment]
This issue has been changed but still is not working properly as is expected!!
![image](https://user-images.githubusercontent.com/88825506/129375936-46f3eeb8-006b-4b2d-9334-413c6311587e.png)

**Comment by RezaUFC** [comment]
Done
