### ISSUE TITLE
Visual Issue - Setting / Call System

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#50]
Please make sure all the lines and texts are in their own right place with the correct distance. 
As you can see in the screenshot, the red text for credit balance is too close to the below line and too far from the above line. 

![image](https://user-images.githubusercontent.com/88825506/130049359-a649a14f-15f7-4ed8-9b09-a895377cbab6.png)

**Comment by harmeetsinghD4D** [comment]
this is fix now 

![image](https://user-images.githubusercontent.com/68951644/130050375-8022a3dc-08cd-42e9-ae8f-e72d3512fe15.png)
