### ISSUE TITLE
Add $ sign to Add Credit input

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#51]
It will be more convenient for users to have an idea of what is exactly this input number, 
It just needs to be added a $ sign before the number!

![image](https://user-images.githubusercontent.com/88825506/130053073-829b4bc0-67b5-4737-8808-921c68775fa2.png)

**Comment by navid-farjad** [comment]
write under input: 
Total fee: 100 USD

**Comment by RezaUFC** [comment]
Done
