### ISSUE TITLE
NEW 11 - Pricing Button Issue 

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#52]
The button is working at some special action of click, Please see the video below to understand exactly the issue. 

https://user-images.githubusercontent.com/88825506/130053716-a0a4a16a-af90-4ad2-a3db-742b35074f35.mp4

**Comment by pureinx** [comment]
@navid-farjad I think this is Harman issue

**Comment by RezaUFC** [comment]
Text color issue 

![image](https://user-images.githubusercontent.com/88825506/130251954-9879afdf-a2f8-4292-ba5a-5e17cf1a6462.png)

![image](https://user-images.githubusercontent.com/88825506/130252080-286f29a6-409b-4c6a-a9ec-522a31917d75.png)

**Comment by pureinx** [comment]
@RezaUFC Could you record a video? I cannot catch this bug

**Comment by RezaUFC** [comment]
Done, now is showing with correct color,
