### ISSUE TITLE
Closing Ticket Issue

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#58]
After the conversation ticket is done and closed by the agent, user will receive a review stars and the feedback, after submitting feedback the chat must be disabled for the user to not send any more messages. which as now this is not working properly !!!

![image](https://user-images.githubusercontent.com/88825506/130061850-4dcbcadc-e5cc-4b44-a882-bc5249994a73.png)

**Comment by pureinx** [comment]
@RezaUFC can you record a video for this issue? I cannot catch it.

**Comment by RezaUFC** [comment]
https://user-images.githubusercontent.com/88825506/130075429-db9db5b8-f337-4bcd-bfa8-e1aa5d385117.mp4


https://user-images.githubusercontent.com/88825506/130075448-2add6aec-582d-4850-b795-cce61a299703.mp4


https://user-images.githubusercontent.com/88825506/130075459-2b070e9a-1af9-46e0-bb82-3b7467014b2b.mp4

**Comment by navid-farjad** [comment]
@RezaUFC mention @pureinx in comments when you have update for him

**Comment by RezaUFC** [comment]
@pureinx  In case is possible please make this white box totally disappear and the messages extend to replace that empty space. 

![image](https://user-images.githubusercontent.com/88825506/130205472-6d4bd7c8-cb9c-4bbb-b34d-fab5e61020aa.png)

**Comment by RezaUFC** [comment]
@pureinx  Closing ticket still has the same issue, Plus new issue which after submitting review stars and feedback, again user can change the rating stars and open chat to type feedback again. 


https://user-images.githubusercontent.com/88825506/130260249-db5c653f-9fb8-4a3f-b097-49bdbd7f3ec3.mp4

**Comment by pureinx** [comment]
@RezaUFC should be fixed, can you check again please?

**Comment by RezaUFC** [comment]
There is a new issue again, Stars are not clickable and I cant select the number of stars, submitting feedback does not close the conversation for text typing 


https://user-images.githubusercontent.com/88825506/130347048-ae838b76-6304-4fc1-9d28-e50e2532ea74.mp4
