### ISSUE TITLE
copy ticket

### ISSUE THREAD

**Issue by navid-farjad** [navid-farjad/yollochat#59]
there is a copy icon on ticket id, what this should actually do is:
 generate a link like: yollochat.com?ticket_id=893
then copy it to the clipboard 

on loading website, we should check for ticket_id in URL and open a tab with that ticket
![image](https://user-images.githubusercontent.com/30972233/130070910-7b04aa5a-1f50-4f4b-b5b8-8ab9875a23f8.png)

**Comment by RezaUFC** [comment]
This Feature is not working, 
After copy the ticket ID the copied link has a different ticket id on the URL

![image](https://user-images.githubusercontent.com/88825506/130188935-07f5d4d0-f486-4854-9d2f-d1b8048907be.png)

![image](https://user-images.githubusercontent.com/88825506/130189002-e8ee1bba-d86e-4115-9a83-3b619e39a2d8.png)

**Comment by RezaUFC** [comment]
@pureinx  / you need to remove local host and replace it with yollochat.com , in this case will work

**Comment by RezaUFC** [comment]
Done!
