### ISSUE TITLE
show text on hover

### ISSUE THREAD

**Issue by navid-farjad** [navid-farjad/yollochat#60]
some of the texts are not very visible if they are wrong in ticket events, we should show the description on a tooltip on hover,

![image](https://user-images.githubusercontent.com/30972233/130071213-2af7bfa7-fb1f-442c-9a4c-2077b6a2af0f.png)

**Comment by navid-farjad** [comment]
@pureinx iam not sure if its Harman part or not

**Comment by pureinx** [comment]
@navid-farjad we have tooltips there but it not displaying, something wrong with styles
