### ISSUE TITLE
Report Analysis Issue

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#62]
the reporting analysis is not updating accurately, At the first step only the information will be updated in case of changing the dates, secondly, the graphs are not ending with the same selected date as you can see on the screen shoot!!!!! 

![image](https://user-images.githubusercontent.com/88825506/130084193-b62ee97d-aa84-4346-83f9-74553130d82f.png)

**Comment by navid-farjad** [comment]
@pureinx for report pages default calendar value should be last 3 months

**Comment by RezaUFC** [comment]
Done
