### ISSUE TITLE
Timezone of Messages and my pc is not the same. 

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#63]
![image](https://user-images.githubusercontent.com/88825506/130085568-6aebb91c-cd7b-4059-bec0-fb0e571b88ba.png)

**Comment by navid-farjad** [comment]
@pureinx i cant fix issue from backend , iam indexing the time i cant convert it easily . i think its much better you do it on front end 
you have timezone in account object , just change all ticket and messages times by that , we need a common function for it

**Comment by RezaUFC** [comment]
Done
