### ISSUE TITLE
Call from Live visitor to Agent is not working!!!!

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#67]
A live visitor is calling to an agent, on the mini chat there is a calling screen, but, the agent does not receive anything on the dashboard. 

https://user-images.githubusercontent.com/88825506/130195390-1fe9dfb4-10ba-4c32-a304-c71f339c6914.mp4

**Comment by pureinx** [comment]
@navid-farjad backend issue, I didnt receive nothing from SalesChannel when visitor is calling.

**Comment by navid-farjad** [comment]
@pureinx but it's the same function that I didn't change! magic

**Comment by navid-farjad** [comment]
@pureinx the issue was he tested in incognito
