### ISSUE TITLE
mini chat notification

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#7]
## Expected Behavior
Showing the last message of agent plus avatar to the visitor after they close the mini chat but the conversation is in process. 

receiving notification with sound and last message. 
## Current Behavior

nothing is appearing if the mini chat is close and the agent is sending a message to the visitor. 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by pureinx** [comment]
@RezaUFC please retest it after new changes is deployed

**Comment by RezaUFC** [comment]
Not Working yet. the last agent message is coming just to the box, I mean after opening the minichat only you can see

**Comment by RezaUFC** [comment]
This issue still has the same, which it mean that when minichat is close, if agent sending message the popup message does not show.

**Comment by RezaUFC** [comment]
This function still is not working!!!
