### ISSUE TITLE
Extra tabs dropdown Icon Not Visible !!!

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#71]
![image](https://user-images.githubusercontent.com/88825506/130214913-1f7add24-5488-4ec3-a3ec-1ff25a07c00d.png)

**Comment by harmeetsinghD4D** [comment]
it's fixed now 
![image](https://user-images.githubusercontent.com/68951644/130236449-3d349334-f8fe-4060-8f6a-813d31af7816.png)

**Comment by RezaUFC** [comment]
Done
