### ISSUE TITLE
Calling issue Agent to open ticket

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#73]
Call bar after connected, it will show 1s and will disappear from mini chat but call is still going on till agent cut it. 

https://user-images.githubusercontent.com/88825506/130251125-17bb44fd-0aff-44dc-ba87-6464aabaaa60.mp4

**Comment by pureinx** [comment]
@RezaUFC Is it first time call or not?

**Comment by RezaUFC** [comment]
@pureinx no is not first time call, I think I try 3 time even reload the page just to make sure

**Comment by pureinx** [comment]
@RezaUFC Can you test it again? Should be fixed.

**Comment by RezaUFC** [comment]
Done
