### ISSUE TITLE
Mini chat - load issue

### ISSUE THREAD

**Issue by harmeetsinghD4D** [navid-farjad/yollochat#79]
![image](https://user-images.githubusercontent.com/68951644/130603484-c66efcd8-8e46-4026-89c2-7c406a784ad3.png)
![image](https://user-images.githubusercontent.com/68951644/130603549-b9831ffe-c1b3-4540-ade9-c761529bf4a3.png)

**Comment by pureinx** [comment]
@harmeetsinghD4D clear local storage and try to catch this error again please

**Comment by RezaUFC** [comment]
Done
