### ISSUE TITLE
User name is incorrect

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#87]
Why is this happened ? I have started the ticket and it shows the name Harman Test as user name which I put Reza as the name

![image](https://user-images.githubusercontent.com/88825506/132521707-12292588-ae4a-433f-9eb6-3605eea8f98b.png)

**Comment by pureinx** [comment]
I need a recorded video for this issue, because i cant catch it.

**Comment by pureinx** [comment]
@RezaUFC

**Comment by RezaUFC** [comment]
This happens when I opened the website from incognito chrome, I think in this case we need to make the chat unavailable if someone is trying to start a chat in incognito.

**Comment by RezaUFC** [comment]
Done
