### ISSUE TITLE
Minichat opening ticket issue

### ISSUE THREAD

**Issue by RezaUFC** [navid-farjad/yollochat#9]
## Expected Behavior
one for to show without scrolling 

## Current Behavior

There is two forms on top of each other. 
![image](https://user-images.githubusercontent.com/88825506/129190636-3aeb9c27-0ab7-4824-bc67-e770db431738.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by navid-farjad** [comment]
deployed

**Comment by RezaUFC** [comment]
Done, It's working as is expected.
